### ISSUE TITLE
Gradle 5.0 Support

### ISSUE THREAD

**Issue by trevorism** [Ullink/gradle-nunit-plugin#51]
Great plugin.
Updating to Gradle 5.0 gives: You must install NUnit and set nunit.home property or NUNIT_HOME env variable. Expression: nunitExec.isFile()

Setting the NUNIT_HOME environment variable has no affect.

My configuration:
nunit {
    nunitVersion = '3.7.0'
    testAssemblies = ["$buildDir/msbuildSolution/bin/${testProjectName}.dll"]
}
Stack Trace:
Caused by: java.lang.AssertionError:
        at com.ullink.gradle.nunit.NUnit2Mixins.getNunitExec(NUnit2Mixins.groovy:26)
        at com.ullink.gradle.nunit.NUnit.run(NUnit.groovy:263)

**Comment by ngyukman** [comment]
hi @trevorism 

something strange is that it is taking NUnit2Mixins instead of NUnit3Mixins as say in https://github.com/Ullink/gradle-nunit-plugin/blob/master/src/main/groovy/com/ullink/gradle/nunit/NUnit.groovy#L91

**Comment by tephe** [comment]
I did an update to gradle 5.0 https://github.com/tephe/gradle-nunit-plugin/commit/b7d02f36ed17b56d9f001bcf7ef5480fab837a2f . Currently waiting for https://github.com/Ullink/gradle-nunit-plugin/pull/53 to be merged so I can open a new pull request and discuss more about this in detail, because there is a breaking change for **timeout** field.

**Comment by trevorism** [comment]
This is now working on the latest release (1.14) -- so this issue can be closed
